### PR TITLE
add build and config disable/header check and fix c nits

### PR DESCRIPTION
**Pull request by baallan**

### CODE REVIEW

**Comment by baallan** [comment]
@andyw-lala build is ready for you to merge.

**Comment by baallan** [comment]
after merge,
./autogen.sh
./configure --enable-tx2mon
make -j

**Comment by baallan** [comment]
we have a library with header ldms/src/ldmsd/ldmsd_plugattr.h
which I recommend for any option parsing, though frankly I can't see what options you would want to parse unless you want to support some sort of config file that filters out unwanted values from the data structure.
The store_csv used ldmsd_plugattr if you need an example.

**Comment by andyw-lala** [comment]
Thanks - glad this process flow is working.

Build on tx2 login node works, but on an x86 host, I get:
```
andyw@ermintrude:hpe/andyw-ovis$ ./configure --enable-tx2mon
checking for gcc... gcc
...
checking readline/history.h presence... yes
checking for readline/history.h... yes
checking tx2mon/mc_oper_region.h usability... no
checking tx2mon/mc_oper_region.h presence... no
checking for tx2mon/mc_oper_region.h... no
configure: error: tx2mon/mc_oper_region.h not found.
use --disable-tx2mon except on thunderx2 with the tx2mon package installed.
andyw@ermintrude:hpe/andyw-ovis$
```
Is this because of a  test that you placed in the configure stuff ?

**Comment by baallan** [comment]
that's exactly the behavior expected. 

grep -i tx2mon configure.ac 

will show you where.

**Pull request merged**
